auth:
  base-url: http://localhost:8180/auth
  realm: stiwa
  realm-url: ${auth.base-url}/realms/${auth.realm}
  jwk-set-uri: ${auth.realm-url}/protocol/openid-connect/certs


security:
  oauth2:
    client:
      clientId: ${auth.client-id}
      clientSecret: ${auth.client-secret}
      accessTokenUri: ${auth.access-token-uri}
      userAuthorizationUri: ${auth.realm-url}/protocol/openid-connect/auth
      #user-name-attribute: preferred_username
      scope: openid, profile
      #tokenName: oauth_token
      #authenticationScheme: query
      #clientAuthenticationScheme: form
    resource:
      user-info-uri: ${auth.realm-url}/protocol/openid-connect/userinfo
      #token-info-uri: ${auth.realm-url}/protocol/openid-connect/token/introspect
      #id: openid
      #jwt:
        #key-uri: ${auth.realm-url}/protocol/openid-connect/certs
        #key-set-uri: ${auth.realm-url}/protocol/openid-connect/introspect